project:
  type: website
  output-dir: docs
  render:
    - index.qmd           
    - training/
    - methods/
    - workshop/
    
website:
  title: "EFSPI Statistical Methodology Leaders"
  navbar:
    background: info
    left:
    # - text: "EFSPI regulatory statistics workshop"
    #   href: https://efspieurope.github.io/workshop/
    # - text: "EFSPI trainings: Calendar of events"
    #   menu:
    #     - text: "Upcoming"  
    #       href: training/events_upcoming.html
    #     - text: "Past"  
    #       href: training/events_past.html
    - text: "Members"  
      href: methods/methods_members.html
    - text: "Events"  
      href: methods/events.html
    - text: "Priority topics"  
      href: methods/priority.html
    - text: "Publications"  
      href: methods/publications.html
    - text: "Newsletters"  
      menu:
        - text: "3rd March 2025"  
          href: methods/20250304_news.html
        - text: "14th February 2026"  
          href: methods/20260214_achievements2025.html
        - text: "12th June 2026"  
          href: methods/20260612_news.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source


