project:
  type: website
  output-dir: docs
  render:
    - index.qmd           
    - training
    - methods
    - workshop
    
website:
  title: "EFSPI Europe"
  navbar:
    background: info
    left:
    - text: "EFSPI regulatory statistics workshop"
      href: workshop/workshop_intro.html
    - text: "EFSPI trainings: Calendar of events"
      menu:
        - text: "Upcoming"  
          href: training/events_upcoming.html
        - text: "Past"  
          href: training/events_past.html
    - text: "EFSPI statistical methodology leaders"
      menu:
        - text: "Introduction"  
          href: methods/methods_intro.html
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source


