project:
  type: website
  output-dir: docs
  render:
    - index.qmd           
    - training/
    - methods/
    - workshop/
    
website:
  title: "EFSPI Statistical Methodology Leaders"
  navbar:
    background: info
    left:
    # - text: "EFSPI regulatory statistics workshop"
    #   href: https://efspieurope.github.io/workshop/
    # - text: "EFSPI trainings: Calendar of events"
    #   menu:
    #     - text: "Upcoming"  
    #       href: training/events_upcoming.html
    #     - text: "Past"  
    #       href: training/events_past.html
    - text: "Resources"
      menu:
        - text: "Members"  
          href: methods/methods_members.html
        - text: "Events"  
          href: methods/events.html
        - text: "Priority topics"  
          href: methods/priority.html
        - text: "Publications"  
          href: methods/publications.html
        - text: "Newsletters"  
          href: methods/newsletters.html
         
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      sidebar-width: 400px
      body-width: 1300px
      margin-width: 400px

editor: source


