---
title: "Newsletter 12th June 2026"
date: last-modified
execute:   
  freeze: auto  # re-render only when source changes
format:
  html:
    toc: true
    toc-depth: 3
    number-sections: false
    highlight-style: pygments
---

# Events 

## Yearly face-to-face meeting

In April, the EFSPI statistical methodology leaders met for their yearly face-to-face meeting in Copenhagen. The meeting was co-organized by Novo Nordisk and Lundbeck. Ten members took two days out of their busy schedule to travel to Denmark. These [topics](events.html#efspi-statistical-methodology-leaders-f2f-in-copenhagen) were discussed.

## Meeting with EMA statisticians

The EML have met with EMA statisticians on 19th May 2026 and discussed the following topics:

- Open question to regulators: What gaps do you observe that we could help improve?
- Covariate adjustment.
- The minutes of this meeting are available [here](events/20260519/20260519_EML_EMA_stats.pdf).

## And more

See [events page](events.html).

# Evolvement of priority topics

See [priority topics](priority.html). The page provides the charter for each priority topic, and these charters outline mission, key stakeholders, workplan, deliverables, and timelines. We are wrapping up the priority topic _A framework to appraise statistical methods building on ICH M15_ and have added _AI_ as a priority topic.

# Paper _Statistical Methodology Groups in the Pharmaceutical Industry_

Led by Jenny Devenport the group has written this [paper](https://doi.org/10.1080/19466315.2026.2656249). The journal ([Statistics in Biopharmaceutical Research](https://www.tandfonline.com/journals/usbr20)) has decided to make this a discussion paper and invited three discussants:

- [Jose Pinheiro](https://doi.org/10.1080/19466315.2026.2658638).
- [Steven Snapinn](https://doi.org/10.1080/19466315.2026.2656255).
- [ASA Biopharmaceutical working group, Statistical Innovation Community](https://doi.org/10.1080/19466315.2026.2661384).
- [Our rejoinder](https://doi.org/10.1080/19466315.2026.2663697).

The paper explores the setup, remit, and value of dedicated methodology groups, alongside the critical organizational considerations and success factors required to maximize their impact on the speed, efficiency, and probability of success.

The paper has also been discussed in [this episode](https://theeffectivestatistician.com/the-future-of-statistical-methodology-in-drug-development/) of the [Effective Statistician podcast](https://theeffectivestatistician.com/).

