---
title: "Newsletter 18th May 2026"
date: last-modified
execute:   
  freeze: auto  # re-render only when source changes
format:
  html:
    toc: true
    toc-depth: 3
    number-sections: false
    highlight-style: pygments
---

# Yearly face-to-face meeting

In April, the EFSPI statistical methodology leaders met for their yearly face-to-face meeting at Merck in Copenhagen. Ten members took two days out of their busy schedule to travel to Denmark. These [topics](events.html#efspi-statistical-methodology-leaders-f2f-in-copenhagen) were discussed.

# Events

See [events page](events.html).

# Evolvement of priority topics

See [priority topics](priority.html).

# Paper _Statistical Methodology Groups in the Pharmaceutical Industry_

Led by Jenny Devenport the group has written this [paper](https://doi.org/10.1080/19466315.2026.2656249). The journal ([Statistical in Biopharmaceutical Research](https://www.tandfonline.com/journals/usbr20)) has decided to make this a discussion paper and invited three discussants, see their contributions here (available online around end of May).

The paper explores the setup, remit, and value of dedicated methodology groups, alongside the critical organizational considerations and success factors required to maximize their impact on the speed, efficiency, and probability of success.

