---
title: "Priority topics"
date: last-modified
execute:   
  freeze: auto  # re-render only when source changes
format:
  html:
    toc: true
    toc-depth: 3
    number-sections: false
    highlight-style: pygments
tbl-colwidths: [15, 10, 35, 10, 10]
---

Currently, the EFSPI methods leaders are working on five priority topics. These are aligned with overall EFSPI priorities.



```{r setup, include = FALSE, echo = FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)

## read in data
path <- getwd()
prio <- as.data.frame(read_excel(paste(path, "/material/prio.xlsx", sep = ""), col_types = NULL))
```



```{r, include=TRUE, echo=FALSE}
#| label: fig-posSens
#| fig-cap: "Probability of success (incl. 90% combined regulatory-tolerability-reduction) displayed over values for weights of Components 1 and 2 with chosen weight highlighted."
#| out-width: "100%"
#| tbl-align: center

prio[is.na(prio)] <- ""
kable(prio, align = "llll", row.names = FALSE)
```





