---
title: "EFSPI regulatory statistics workshop"
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: no
    self_contained: yes
    toc: no
    toc_depth: 2
    toc_float: yes
---

# EFSPI regulatory statistics workshop

Each year, a small team of volunteers organizes the [EFSPI Regulatory Statistics Workshop](http://www.efspiworkshop.org) on behalf of [EFSPI](http://www.efspi.org). The goal of the workshop is to bring together statisticians and partner functions from pharmaceutical industry, regulatory agencies, and academia to discuss topics of common interest.

The unique feature of the workshop is an atmosphere of collaboration and open discussion of statistical and regulatory science in general. Over the years the workshop has sharpened its profile and with regular participation of speakers from regulatory agencies such as EMA, many European regulatory agencies, FDA, PMDA, MHRA, and many more has become a voice in the global dialogue on regulatory statistics. Furthermore, with HTA considerations becoming ever more important in Europe and beyond topics pertinent to HTA are also increasingly discussed.

Since its inception in 2016 the workshop has always taken place in Basel, Switzerland. 

Find slidedecks and recordings of past events as well as information about the upcoming event on the [workshop webpage](http://www.efspiworkshop.org).

# Feedback 

For feedback and questions send an email to [efspieurope@gmail.com](efspieurope@gmail.com).



